"""modify consultation model

Revision ID: 2f6d56473ddc
Revises: 0d0ca6408c25
Create Date: 2021-04-16 15:41:39.105688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6d56473ddc'
down_revision = '0d0ca6408c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('consultations', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'status')
    op.drop_column('consultations', 'details')
    # ### end Alembic commands ###
