"""modify speciality name column

Revision ID: 49d8057a0b72
Revises: 7ed6b0687fcb
Create Date: 2021-04-16 11:39:52.921784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d8057a0b72'
down_revision = '7ed6b0687fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialities', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialities', type_='unique')
    # ### end Alembic commands ###
