"""update patient model

Revision ID: 4dfa3c3d0751
Revises: d2ae23148e50
Create Date: 2021-04-15 23:09:41.547946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfa3c3d0751'
down_revision = 'd2ae23148e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'password_hash')
    # ### end Alembic commands ###
