"""create speciality model add relationship into doctor_model

Revision ID: 7ed6b0687fcb
Revises: 6fe4ae9b01bb
Create Date: 2021-04-15 23:50:54.783513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ed6b0687fcb'
down_revision = '6fe4ae9b01bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doctors', sa.Column('speciality_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'doctors', 'specialities', ['speciality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'speciality_id')
    op.drop_table('specialities')
    # ### end Alembic commands ###
